
CREATE TABLE IF NOT EXISTS DEVICE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DevEUI VARCHAR(16) NOT NULL UNIQUE,
    AppEUI VARCHAR(16),
    AppKey VARCHAR(32) NOT NULL,
    DevNonce INTEGER DEFAULT 1,
    DevAddr VARCHAR(8),
    NwkSKey VARCHAR(32),
    AppSKey VARCHAR(32),
    FCnt INTEGER DEFAULT 1,
    FPort INTEGER DEFAULT 1,
    Created_at TIMESTAMP DEFAULT (DATETIME('now','utc'))
);


INSERT INTO DEVICE(    
    DevEUI,
    AppKey
) VALUES(
    "b53fcaaa8725fe1b",
    "45abd993fa42864305fd20b63b21b80d"
);